### ISSUE TITLE
Skywallet branding

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#156]
**Feature description**

Reference SkyWallet .

**Is your feature request related to a problem? Please describe.**
The inherited technology is mentioned all over across the project tree .

**Additional context**
noticed after merging #147 

**Possible implementation**

- [x] rename source files
- [x] update file contents
- [x] ensure output binary files are created with correct names

**Comment by stdevMac** [comment]
Should I also change trezor in self-generated comments? Example, if I change the file, since the names of `trezor.h` are changed to `skywallet.h` and all its occurrences, then what do I do with the files in which they are autogenerated or signed with the license, which are modified? I delete the trazor comment or do I leave it?

Example here: https://github.com/simelo/skycoin-hardware-wallet/pull/3/files#diff-a84e671dd7e5ccabf6783b42f67d4c13

**Comment by stdevMac** [comment]
Which are the other places that i should change?

**Comment by olemis** [comment]
fixed in 50000f6
