### ISSUE TITLE
Test coverage for v1

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#208]
**Feature description**

test coverage and hardening needed before releasing v1

**Is your feature request related to a problem? Please describe.**
Some paths in firmware are not tested 

**Describe the solution you'd like**
More test cases and, if feasible, test coverage reports.

**Describe alternatives you've considered**
To be honest no other options considered . Open to suggestions .

**Additional context**
It all started when I detected address generation without mnemonic did not have a test case in firmware .

**Possible implementation**

- [x] Identify untested test paths, and add tasks
- [x] Write test cases
- ~Setup compilation with test coverage~ see #212 
- ~Generate coverage reports~ see #212 

Test scenarios identified

- [x] Generate address without mnemonic set
- [x] Internal entropy should always be `0` beyond firmware function boundaries.
- [x] Entropy pool mixer should change state after processing `EntropyAck` message
- [x] Unit tests for `serialno.c`
- ~Unit tests for `signatures.c`~
- [ ] Unit tests for `reset.c`
- ~Unit tests for `recovery.c`~ see #315 
- [x] Setting `usePassphase` in `Recovery` message leads to generating wrong addresses
- [x] Label erased after device recovery

**Comment by olemis** [comment]
@Senyoret1 @therealssj please feel free to suggest test scenarios that need to be tested before v1 .

**Comment by stdevStark** [comment]
> * Unit tests for `signatures.c`

@olemis this is difficult to test

**Comment by stdevStark** [comment]
> * Unit tests fir `reset.c`

`reset_init` waits for user to write data .
@olemis can we test it ?

**Comment by olemis** [comment]
@stdevStark Not now without some refactorings we won't be doing in v1 , see #191 #178

**Comment by stdevAlDen** [comment]
> **Feature description**
> 
> test coverage and hardening needed before releasing v1
> 
> **Is your feature request related to a problem? Please describe.**
> Some paths in firmware are not tested
> 
> **Describe the solution you'd like**
> More test cases and, if feasible, test coverage reports.
> 
> **Describe alternatives you've considered**
> To be honest no other options considered . Open to suggestions .
> 
> **Additional context**
> It all started when I detected address generation without mnemonic did not have a test case in firmware .
> 
> **Possible implementation**
> 
> * [x]  Identify untested test paths, and add tasks
> * [ ]  Write test cases
> * ~Setup compilation with test coverage~ see #212
> * ~Generate coverage reports~ see #212
> 
> Test scenarios identified
> 
> * [x]  Generate address without mnemonic set
> * [x]  Internal entropy should always be `0` beyond firmware function boundaries.
> * [x]  Entropy pool mixer should change state after processing `EntropyAck` message
> * [x]  Unit tests for `serialno.c`
> * ~Unit tests for `signatures.c`~
> * [ ]  Unit tests fir `reset.c`
> * [ ]  Unit tests for `recovery.c`

I'm having some issues running the following tests(at the right side of the arrow you can found a possible root cause):
- [ ] `SKY_cipher_PubKey_Verify` --> TestAddressVerify
- [ ] `TestPubKeyFromHex` --> TestNewPubKey and void tobuff(const char* str, uint8_t* buf, size_t bufferLength) do not make validations looking for valid characters
 - [ ] `TestNewPubKey` --> SKY_cipher_PubKey_Verify
 - [ ] `TestAddressVerify` --> unable to find secp256k1.VerifyPubkey
 - [ ] `TestPubKeyVerifyNil` --> SKY_cipher_PubKey_Verify
 - [ ] `TestPubKeyToAddress2` --> unable to find secp256k1.VerifyPubkey
 - [ ] `TestMustSigFromHex` --> void tobuff(const char* str, uint8_t* buf, size_t bufferLength) do not make validations looking for valid characters
 - [ ] `TestPubKeyFromSecKey` --> void generate_pubkey_from_seckey(const uint8_t* seckey, uint8_t* pubkey) do not check for a null seckey
 - [ ] `TestECDHonce` ???
 - [ ] `TestECDHloop` --> TestECDHonce
 - [ ] `TestSHA256KnownValue` --> a possible bug in hash function
 - [ ] `TestSHA256FromHex` --> void tobuff(const char* str, uint8_t* buf, size_t bufferLength) do not make validations looking for valid characters
 - [ ] `TestAddressBulk` --> TestAddressVerify
 - [ ] `TestNewPubKey` --> SKY_cipher_PubKey_Verify

**Comment by jdknives** [comment]
@olemis This has not been touched for a while. (Or rather the PR #209 ) If Stark cannot do it for some reason, one of the Ukrainian team members could give this a shot.

**Comment by olemis** [comment]
> If Stark cannot do it for some reason, one of the Ukrainian team members could give this a shot.

@stdevStark should be finishing tests for `reset.c` , he's been working on the other issues assigned to the Ukranian team .

**Comment by stdevAlDen** [comment]
> > If Stark cannot do it for some reason, one of the Ukrainian team members could give this a shot.
> 
> @stdevStark should be finishing tests for `reset.c` , he's been working on the other issues assigned to the Ukranian team .
> 
> @stdevAlDen is figuring out if tests for `recovery.c` are feasible for v1 . In case there's no straightforward manner to get this done soon , we'll defer that until after v1 .

@olemis I check this as solved but actually I move it to a different issue, [here](https://github.com/skycoin/hardware-wallet/issues/315) the details, pls consider this for the next release.
