### ISSUE TITLE
Update crypro library with Bitcoin operations

### ISSUE THREAD

**Issue by Midren** [skycoin/hardware-wallet#44]
For Bitcoin integration, we need to add all crypto-related functions, that are needed for Bitcoin but are not used in Skycoin. We need to use the functions from [trezor](https://github.com/trezor/trezor-mcu) implementation to be sure, that they work well

- [x] Investigate which functions should be added to our crypto library
- [ ] Add them to our library
- [ ] Write tests to be sure, that they are working well.

**Comment by Macrosrider** [comment]
At the moment, there is no reason to update crypto library, because all crypto, we need, is already implemented. But:
 -  BTC address generation method is a bit different (actually, the order of hashing and version byte positions are different)
 -  There is no P2PKH or P2SH in Skycoin
 - For transaction signing, Skycoin use Binary encodind, BTC use DER encoding instead. But, in skycoin-api/tools/ecdsa.c there is ecdsa_sig_to_der() function, which convert Binary encoding to DER
